### ISSUE TITLE
maxcollateral configuration

### ISSUE THREAD

**Issue by MarkoPaasila** [siacentral/host-manager#51]
I don't see an option to configure _maxcollateral_. It seems to be the only way to limit the size (in Bytes) of a contract - which is important to me as a big contract saturates my internet connection for a month.

For some reason, if I set _maxcollateral_ with ´siac host config maxcollateral´, it is soon changed back to the earlier value - possibly by the running host-manager. So is there a field for _maxcollateral_ which I just haven't noticed?

**Comment by n8maninger** [comment]
There is not, it was pruned when the screen was redone since it's a little confusing with how it works. It's now calculated to allow a maximum of 2TB per contract based on your max duration and collateral. The plan is to simplify the base settings even further and offer an "advanced" mode for power users, I just created #52 to track it.

`maxcollateral` won't do much to limit your usage, renters will just form multiple contracts with you. Instead you should look at setting a rate limit with `siac ratelimit`.

**Comment by MarkoPaasila** [comment]
Thanks! Does host-manager still incidentally configure maxcollateral even though it is removed from the front-end?

What I was trying to solve with maxcollateral wasn't bandwidth, but that one single big contract sets the price for a whole month, because it saturates my capacity. But yes, maxcollateral won't solve the problem as the peer can simply do the same by making many contracts.

**Comment by n8maninger** [comment]
It should only be updating if collateral is pinned
