### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by MeijeSibbel** [siacentral/host-manager#6]
Here are some minor UI issues:

1.

![image](https://user-images.githubusercontent.com/11735738/64739922-d5c35300-d4f3-11e9-81e7-41f0e25f509d.png)

The user can't see all info on the pop-up and also can't scroll down. The only option to see the buttons at the bottom of the popup is to increase the window size.

2. Allow option to clean notifications. Currently the only way to clean notifications is to restart the application. It would be nice to be able to clear any old notifications.

**Comment by n8maninger** [comment]
@MeijeSibbel the notifications are designed to stay around until they are resolved. The contract ones specifically will only go away once the host bugs are fixed in the Daemon. Which notification is going away after a restart? It should pop right back up unless a restart fixed the problem.

I might want to switch that to a more traditional "notification" format instead of what are really "Alerts" that should be resolved not dismissed. That may make it easier to work with. Thoughts?

**Comment by n8maninger** [comment]
I pulled the second issue into #7 since the primary issue is fixed by 5422b21 and I'm not really sure about clearing notifications
