### ISSUE TITLE
Still issues with an IPv6 Host adresse

### ISSUE THREAD

**Issue by Bubbu17** [siacentral/host-manager#62]
Hello, 

meanwhile I Updatet my host and gave it a DNS adresse (siahost.srvdns.de) but off course in the background it still works with the IPv6 adresse.

-The IPv6 Adresse at the DNS Service is correct.
-The Prots in the Router are set correctly to the targest Host Machine
-DNS Forwarding in the Router is enabeld

so i dont see any issue on may side...?

The host dosen't show up on the https://siastats.info/hosts_map why is that? How can I fix this?

https://troubleshoot.siacentral.com/sia/siahost.srvdns.de:9982?unit=decimal&currency=eur

![image](https://user-images.githubusercontent.com/62136070/123394585-94544880-d59f-11eb-889f-718bf493c8c3.png)

Thanks in advance Torsten

**Comment by n8maninger** [comment]
"Permission denied", is usually an issue with your firewall/isp blocking inbound traffic on the port. https://superuser.com/questions/282976/ssh-over-ipv6-got-permission-denied-error

I don't run SiaStats, you should reach out to Hakkane on Discord for issues with SiaStats.

If you need help with firewall or routing I suggest you ask in Discord, we've got a very helpful community there: https://discord.gg/sia

Closing since this is not an issue with Host Manger.

**Comment by Bubbu17** [comment]
Thanks a lot!
